apiVersion : apps/v1
kind: Deployment
metadata:
  name: "clusterop-2a0a"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "clusterop-2a0a"
  template:
    metadata:
      labels:
        app: "clusterop-2a0a"
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: "clusterop-2a0a"
          image: "crservice.azurecr.io/clusterop"
          ports:
          - containerPort: 80
          env:
            - name: REDIS
              value: "clusterop-eeb7"