apiVersion: v1
kind: Service
metadata:
    name: "clusterop-2a0a"
    labels:
        app: "clusterop-2a0a"
spec:
    ports:
    - port: 80
      protocol: TCP
      name: http
    selector:
        app: "clusterop-2a0a"